### ISSUE TITLE
Custom Controller

### ISSUE THREAD

**Issue by dummyjohn77** [ctu-mrs/mrs_uav_controllers#6]
Hi,

Can you please give us an insight on how to use a custom controller that would override MRS-MPC controller, for a given period of time?

Would it also be possible to override without crashing the drone, mid-flight? in the simulations

**Comment by klaxalk** [comment]
Hey, with the new version of the system, you have an option to insert a controller plugin from and external package. The example for that is here: https://github.com/ctu-mrs/mrs_core_examples/tree/master/controller_plugin
